# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Pages deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: '13.x'

    # Runs a single command using the runners shell
    - name: Build
      run: |
        npm ci
        npm run build --modern
    - name: Brotli compress the html, css and js files in the "build" directory
      id: brotli
      uses: charlesworth/compress-action@1.0
      with:
        target-directory: 'dist'
    - name: GitHub Pages deploy
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          cname: mkutnik.com
